{{- if .Values.debugger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.debugger.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Values.debugger.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Values.debugger.name }}  
    spec:
      containers:
      - name: {{ .Values.debugger.name }}
        image: {{ .Values.common.repository }}{{ .Values.debugger.name }}:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: {{ .Values.debugger.limitsMemory | quote }}
            cpu: {{ .Values.debugger.limitsCpu | quote }}
        ports:
          - containerPort: {{ .Values.hats.port }}
            name: http
        env:
{{- with .Values.hats }}
{{ include "service.shared" . | indent 8 }}
{{- end }}
{{ include "common.shared" . | indent 8 }}
        - name: DATASTORE_CONFIG
          value: {{ .Values.hats.datastoreConfig | quote }}
        - name: MONGO_DB
          value: {{ required "missing value hats.mongoDb" .Values.hats.mongoDb | quote }}
        - name: MONGO_URI
          value: {{ required "missing value hats.mongoUri" .Values.hats.mongoUri | quote }}
{{- end }}
  