{{- if .Values.hats.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hats.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Values.hats.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Values.hats.name }}  
    spec:
      containers:
      - name: {{ .Values.hats.name }}
        image: {{ .Values.common.repository }}{{ .Values.hats.name }}:{{ .Values.hats.tag }}
        imagePullPolicy: {{ .Values.common.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.hats.limitsMemory | quote }}
            cpu: {{ .Values.hats.limitsCpu | quote }}
        ports:
          - containerPort: {{ .Values.hats.port }}
            name: http
        volumeMounts:
          - name: {{ .Values.common.pemfileVolume }}
            mountPath: {{ .Values.common.auth0PemfileMount }}
            readOnly: true    
        env:
{{- with .Values.hats }}
{{ include "service.shared" . | indent 8 }}
{{ include "service.rabbit" . | indent 8 }}
{{- end }}
{{ include "common.shared"  . | indent 8 }}
{{ include "common.auth0"   . | indent 8 }}
        - name: MONGO_DB
          value: {{ required "missing value hats.mongoDb" .Values.hats.mongoDb | quote }}
        - name: MONGO_URI
          value: {{ required "missing value hats.mongoUri" .Values.hats.mongoUri | quote }}
      volumes:
        - name: {{ .Values.common.pemfileVolume }}
          secret:
            secretName: {{ .Values.common.name }}
{{- end }}
