{{- if .Values.hats.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hats.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Values.hats.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Values.hats.name }}  
    spec:
      containers:
      - name: {{ .Values.hats.name }}
        image: {{ .Values.common.repository }}{{ .Values.hats.name }}:{{ .Values.hats.tag }}
        imagePullPolicy: {{ .Values.common.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.hats.limitsMemory | quote }}
            cpu: {{ .Values.hats.limitsCpu | quote }}
        ports:
        - containerPort: {{ .Values.hats.port }}
          name: http
        env:
{{- with .Values.hats }}
{{ include "service.shared" . | indent 8 }}
{{- end }}
{{ include "common.shared" . | indent 8 }}
        - name: DATASTORE_CONFIG
          value: {{ .Values.hats.datastoreConfig | quote }}
        - name: REDIS_ADDRESS
          value: {{ .Values.hats.redisAddress | quote }}
        - name: REDIS_PASSWORD
          value: {{ .Values.hats.redisPassword | quote }}
{{- end }}
