// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hats.proto

package hatspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Style int32

const (
	Style_UNKNOWN_STYLE Style = 0
	Style_BOWLER        Style = 1
	Style_FEDORA        Style = 2
	Style_BASEBALL      Style = 3
	Style_NEWSBOY       Style = 4
	Style_COWBOY        Style = 5
	Style_DERBY         Style = 6
	Style_TOP_HAT       Style = 7
)

var Style_name = map[int32]string{
	0: "UNKNOWN_STYLE",
	1: "BOWLER",
	2: "FEDORA",
	3: "BASEBALL",
	4: "NEWSBOY",
	5: "COWBOY",
	6: "DERBY",
	7: "TOP_HAT",
}

var Style_value = map[string]int32{
	"UNKNOWN_STYLE": 0,
	"BOWLER":        1,
	"FEDORA":        2,
	"BASEBALL":      3,
	"NEWSBOY":       4,
	"COWBOY":        5,
	"DERBY":         6,
	"TOP_HAT":       7,
}

func (x Style) String() string {
	return proto.EnumName(Style_name, int32(x))
}

func (Style) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{0}
}

// A Hat is a piece of headwear
type Hat struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Size                 string   `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Color                string   `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Style                Style    `protobuf:"varint,5,opt,name=style,proto3,enum=hats.Style" json:"style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{0}
}

func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (m *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(m, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hat) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Hat) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Hat) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Hat) GetStyle() Style {
	if m != nil {
		return m.Style
	}
	return Style_UNKNOWN_STYLE
}

type MakeHatRequest struct {
	Size                 string   `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Color                string   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Style                Style    `protobuf:"varint,3,opt,name=style,proto3,enum=hats.Style" json:"style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeHatRequest) Reset()         { *m = MakeHatRequest{} }
func (m *MakeHatRequest) String() string { return proto.CompactTextString(m) }
func (*MakeHatRequest) ProtoMessage()    {}
func (*MakeHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{1}
}

func (m *MakeHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeHatRequest.Unmarshal(m, b)
}
func (m *MakeHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeHatRequest.Marshal(b, m, deterministic)
}
func (m *MakeHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeHatRequest.Merge(m, src)
}
func (m *MakeHatRequest) XXX_Size() int {
	return xxx_messageInfo_MakeHatRequest.Size(m)
}
func (m *MakeHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeHatRequest proto.InternalMessageInfo

func (m *MakeHatRequest) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *MakeHatRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *MakeHatRequest) GetStyle() Style {
	if m != nil {
		return m.Style
	}
	return Style_UNKNOWN_STYLE
}

type MakeHatResponse struct {
	Hat                  *Hat     `protobuf:"bytes,1,opt,name=hat,proto3" json:"hat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeHatResponse) Reset()         { *m = MakeHatResponse{} }
func (m *MakeHatResponse) String() string { return proto.CompactTextString(m) }
func (*MakeHatResponse) ProtoMessage()    {}
func (*MakeHatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{2}
}

func (m *MakeHatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeHatResponse.Unmarshal(m, b)
}
func (m *MakeHatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeHatResponse.Marshal(b, m, deterministic)
}
func (m *MakeHatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeHatResponse.Merge(m, src)
}
func (m *MakeHatResponse) XXX_Size() int {
	return xxx_messageInfo_MakeHatResponse.Size(m)
}
func (m *MakeHatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeHatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeHatResponse proto.InternalMessageInfo

func (m *MakeHatResponse) GetHat() *Hat {
	if m != nil {
		return m.Hat
	}
	return nil
}

type ListHatsRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHatsRequest) Reset()         { *m = ListHatsRequest{} }
func (m *ListHatsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHatsRequest) ProtoMessage()    {}
func (*ListHatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{3}
}

func (m *ListHatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHatsRequest.Unmarshal(m, b)
}
func (m *ListHatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHatsRequest.Marshal(b, m, deterministic)
}
func (m *ListHatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHatsRequest.Merge(m, src)
}
func (m *ListHatsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHatsRequest.Size(m)
}
func (m *ListHatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHatsRequest proto.InternalMessageInfo

func (m *ListHatsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListHatsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListHatsResponse struct {
	Hats                 []*Hat   `protobuf:"bytes,1,rep,name=hats,proto3" json:"hats,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHatsResponse) Reset()         { *m = ListHatsResponse{} }
func (m *ListHatsResponse) String() string { return proto.CompactTextString(m) }
func (*ListHatsResponse) ProtoMessage()    {}
func (*ListHatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{4}
}

func (m *ListHatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHatsResponse.Unmarshal(m, b)
}
func (m *ListHatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHatsResponse.Marshal(b, m, deterministic)
}
func (m *ListHatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHatsResponse.Merge(m, src)
}
func (m *ListHatsResponse) XXX_Size() int {
	return xxx_messageInfo_ListHatsResponse.Size(m)
}
func (m *ListHatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHatsResponse proto.InternalMessageInfo

func (m *ListHatsResponse) GetHats() []*Hat {
	if m != nil {
		return m.Hats
	}
	return nil
}

func (m *ListHatsResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListHatsResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Size struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{5}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Size) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListSizesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSizesRequest) Reset()         { *m = ListSizesRequest{} }
func (m *ListSizesRequest) String() string { return proto.CompactTextString(m) }
func (*ListSizesRequest) ProtoMessage()    {}
func (*ListSizesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{6}
}

func (m *ListSizesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSizesRequest.Unmarshal(m, b)
}
func (m *ListSizesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSizesRequest.Marshal(b, m, deterministic)
}
func (m *ListSizesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSizesRequest.Merge(m, src)
}
func (m *ListSizesRequest) XXX_Size() int {
	return xxx_messageInfo_ListSizesRequest.Size(m)
}
func (m *ListSizesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSizesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSizesRequest proto.InternalMessageInfo

type ListSizesResponse struct {
	Sizes                []*Size  `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSizesResponse) Reset()         { *m = ListSizesResponse{} }
func (m *ListSizesResponse) String() string { return proto.CompactTextString(m) }
func (*ListSizesResponse) ProtoMessage()    {}
func (*ListSizesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{7}
}

func (m *ListSizesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSizesResponse.Unmarshal(m, b)
}
func (m *ListSizesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSizesResponse.Marshal(b, m, deterministic)
}
func (m *ListSizesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSizesResponse.Merge(m, src)
}
func (m *ListSizesResponse) XXX_Size() int {
	return xxx_messageInfo_ListSizesResponse.Size(m)
}
func (m *ListSizesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSizesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSizesResponse proto.InternalMessageInfo

func (m *ListSizesResponse) GetSizes() []*Size {
	if m != nil {
		return m.Sizes
	}
	return nil
}

type DeleteHatRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHatRequest) Reset()         { *m = DeleteHatRequest{} }
func (m *DeleteHatRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHatRequest) ProtoMessage()    {}
func (*DeleteHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{8}
}

func (m *DeleteHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHatRequest.Unmarshal(m, b)
}
func (m *DeleteHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHatRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHatRequest.Merge(m, src)
}
func (m *DeleteHatRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHatRequest.Size(m)
}
func (m *DeleteHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHatRequest proto.InternalMessageInfo

func (m *DeleteHatRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteHatRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type DeleteHatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHatResponse) Reset()         { *m = DeleteHatResponse{} }
func (m *DeleteHatResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteHatResponse) ProtoMessage()    {}
func (*DeleteHatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{9}
}

func (m *DeleteHatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHatResponse.Unmarshal(m, b)
}
func (m *DeleteHatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHatResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHatResponse.Merge(m, src)
}
func (m *DeleteHatResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHatResponse.Size(m)
}
func (m *DeleteHatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHatResponse proto.InternalMessageInfo

type FetchHatRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchHatRequest) Reset()         { *m = FetchHatRequest{} }
func (m *FetchHatRequest) String() string { return proto.CompactTextString(m) }
func (*FetchHatRequest) ProtoMessage()    {}
func (*FetchHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{10}
}

func (m *FetchHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchHatRequest.Unmarshal(m, b)
}
func (m *FetchHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchHatRequest.Marshal(b, m, deterministic)
}
func (m *FetchHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchHatRequest.Merge(m, src)
}
func (m *FetchHatRequest) XXX_Size() int {
	return xxx_messageInfo_FetchHatRequest.Size(m)
}
func (m *FetchHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchHatRequest proto.InternalMessageInfo

func (m *FetchHatRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FetchHatResponse struct {
	Hat                  *Hat     `protobuf:"bytes,1,opt,name=hat,proto3" json:"hat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchHatResponse) Reset()         { *m = FetchHatResponse{} }
func (m *FetchHatResponse) String() string { return proto.CompactTextString(m) }
func (*FetchHatResponse) ProtoMessage()    {}
func (*FetchHatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b65fa2650eb6b0bd, []int{11}
}

func (m *FetchHatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchHatResponse.Unmarshal(m, b)
}
func (m *FetchHatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchHatResponse.Marshal(b, m, deterministic)
}
func (m *FetchHatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchHatResponse.Merge(m, src)
}
func (m *FetchHatResponse) XXX_Size() int {
	return xxx_messageInfo_FetchHatResponse.Size(m)
}
func (m *FetchHatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchHatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchHatResponse proto.InternalMessageInfo

func (m *FetchHatResponse) GetHat() *Hat {
	if m != nil {
		return m.Hat
	}
	return nil
}

func init() {
	proto.RegisterEnum("hats.Style", Style_name, Style_value)
	proto.RegisterType((*Hat)(nil), "hats.Hat")
	proto.RegisterType((*MakeHatRequest)(nil), "hats.MakeHatRequest")
	proto.RegisterType((*MakeHatResponse)(nil), "hats.MakeHatResponse")
	proto.RegisterType((*ListHatsRequest)(nil), "hats.ListHatsRequest")
	proto.RegisterType((*ListHatsResponse)(nil), "hats.ListHatsResponse")
	proto.RegisterType((*Size)(nil), "hats.Size")
	proto.RegisterType((*ListSizesRequest)(nil), "hats.ListSizesRequest")
	proto.RegisterType((*ListSizesResponse)(nil), "hats.ListSizesResponse")
	proto.RegisterType((*DeleteHatRequest)(nil), "hats.DeleteHatRequest")
	proto.RegisterType((*DeleteHatResponse)(nil), "hats.DeleteHatResponse")
	proto.RegisterType((*FetchHatRequest)(nil), "hats.FetchHatRequest")
	proto.RegisterType((*FetchHatResponse)(nil), "hats.FetchHatResponse")
}

func init() { proto.RegisterFile("hats.proto", fileDescriptor_b65fa2650eb6b0bd) }

var fileDescriptor_b65fa2650eb6b0bd = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6b, 0x1a, 0x41,
	0x14, 0xed, 0x7e, 0x69, 0xbc, 0xb6, 0x3a, 0x4e, 0x6d, 0xba, 0x58, 0x0a, 0x66, 0x9e, 0xa4, 0x0f,
	0x16, 0x2c, 0x2d, 0x14, 0x02, 0xc5, 0xad, 0x1b, 0x84, 0x5a, 0xb7, 0xac, 0x16, 0xb1, 0x50, 0x64,
	0x93, 0x4c, 0xe2, 0xd2, 0x8d, 0x6b, 0x9c, 0xb1, 0xd0, 0xd0, 0x1f, 0xd5, 0x9f, 0x58, 0x66, 0x76,
	0xc6, 0x8f, 0x8d, 0x81, 0xbc, 0xdd, 0x39, 0xf7, 0xeb, 0xec, 0x39, 0x97, 0x05, 0x98, 0x47, 0x9c,
	0xb5, 0x97, 0xab, 0x94, 0xa7, 0xd8, 0x16, 0x31, 0xf9, 0x0b, 0x56, 0x3f, 0xe2, 0xb8, 0x02, 0x66,
	0x7c, 0xe9, 0x1a, 0x4d, 0xa3, 0x55, 0x0a, 0xcd, 0xf8, 0x12, 0xbb, 0x50, 0xfc, 0x4d, 0x57, 0x2c,
	0x4e, 0x17, 0xae, 0xd9, 0x34, 0x5a, 0x4e, 0xa8, 0x9f, 0x18, 0x83, 0xcd, 0xe2, 0x3b, 0xea, 0x5a,
	0xb2, 0x56, 0xc6, 0xb8, 0x0e, 0xce, 0x45, 0x9a, 0xa4, 0x2b, 0xd7, 0x96, 0x60, 0xf6, 0xc0, 0x27,
	0xe0, 0x30, 0xfe, 0x27, 0xa1, 0xae, 0xd3, 0x34, 0x5a, 0x95, 0x4e, 0xb9, 0x2d, 0x97, 0x8f, 0x04,
	0x14, 0x66, 0x19, 0xf2, 0x13, 0x2a, 0x5f, 0xa3, 0x5f, 0xb4, 0x1f, 0xf1, 0x90, 0xde, 0xae, 0x29,
	0xe3, 0x9b, 0xf1, 0xc6, 0xa1, 0xf1, 0xe6, 0xc1, 0xf1, 0xd6, 0x83, 0xe3, 0xdb, 0x50, 0xdd, 0x8c,
	0x67, 0xcb, 0x74, 0xc1, 0x28, 0x7e, 0x05, 0xd6, 0x3c, 0xe2, 0x72, 0x7c, 0xb9, 0x53, 0xca, 0x7a,
	0x44, 0x5e, 0xa0, 0xe4, 0x13, 0x54, 0x07, 0x31, 0xe3, 0xfd, 0x88, 0x33, 0xcd, 0xa7, 0x0e, 0x4e,
	0x12, 0xdf, 0xc4, 0x59, 0x87, 0x13, 0x66, 0x0f, 0x7c, 0x0c, 0x85, 0xf4, 0xea, 0x8a, 0x51, 0xae,
	0xd4, 0x51, 0x2f, 0x32, 0x03, 0xb4, 0x1d, 0xa0, 0x36, 0xbe, 0x06, 0xa9, 0xb4, 0x6b, 0x34, 0xad,
	0xfd, 0x95, 0x12, 0xde, 0x2e, 0x30, 0x0f, 0x2f, 0xb0, 0xf6, 0x16, 0xb4, 0xc1, 0x1e, 0x09, 0x49,
	0x84, 0x4c, 0xc9, 0xfa, 0x7a, 0x23, 0x53, 0xb2, 0xbe, 0x16, 0xd8, 0x22, 0xba, 0xa1, 0x4a, 0x25,
	0x19, 0x13, 0x9c, 0x11, 0x12, 0x3d, 0xfa, 0x93, 0xc8, 0x7b, 0xa8, 0xed, 0x60, 0x8a, 0x65, 0x13,
	0x1c, 0xa1, 0xb5, 0xa6, 0x09, 0x4a, 0xcd, 0xf8, 0x4e, 0x88, 0x29, 0x12, 0xe4, 0x14, 0x50, 0x8f,
	0x26, 0x94, 0xef, 0xba, 0xf5, 0xe8, 0xb3, 0x21, 0xcf, 0xa1, 0xb6, 0xd3, 0x9d, 0x2d, 0x25, 0x27,
	0x50, 0x3d, 0xa3, 0xfc, 0x62, 0xfe, 0xf0, 0x44, 0xf2, 0x16, 0xd0, 0xb6, 0xe4, 0x11, 0x1e, 0xbe,
	0xb9, 0x05, 0x47, 0xde, 0x00, 0xae, 0xc1, 0xb3, 0xef, 0xc3, 0x2f, 0xc3, 0x60, 0x32, 0x9c, 0x8d,
	0xc6, 0xd3, 0x81, 0x8f, 0x9e, 0x60, 0x80, 0x82, 0x17, 0x4c, 0x06, 0x7e, 0x88, 0x0c, 0x11, 0x9f,
	0xf9, 0xbd, 0x20, 0xec, 0x22, 0x13, 0x3f, 0x85, 0x23, 0xaf, 0x3b, 0xf2, 0xbd, 0xee, 0x60, 0x80,
	0x2c, 0x5c, 0x86, 0xe2, 0xd0, 0x9f, 0x8c, 0xbc, 0x60, 0x8a, 0x6c, 0x51, 0xf6, 0x39, 0x98, 0x88,
	0xd8, 0xc1, 0x25, 0x70, 0x7a, 0x7e, 0xe8, 0x4d, 0x51, 0x41, 0xd4, 0x8c, 0x83, 0x6f, 0xb3, 0x7e,
	0x77, 0x8c, 0x8a, 0x9d, 0x7f, 0x26, 0xd8, 0xc2, 0x72, 0xfc, 0x01, 0x8a, 0xea, 0xde, 0x70, 0x3d,
	0xa3, 0xb5, 0x7f, 0xdd, 0x8d, 0x17, 0x39, 0x54, 0x7d, 0xd0, 0x47, 0x38, 0xd2, 0x67, 0x83, 0x55,
	0x49, 0xee, 0x0e, 0x1b, 0xc7, 0x79, 0x58, 0xb5, 0x9e, 0x42, 0x69, 0x63, 0x26, 0xde, 0x29, 0xda,
	0x75, 0xbc, 0xf1, 0xf2, 0x1e, 0xbe, 0xed, 0xde, 0xb8, 0xa2, 0xbb, 0xf3, 0x26, 0xeb, 0xee, 0x7b,
	0xf6, 0x09, 0xda, 0xda, 0x1b, 0x4d, 0x3b, 0x67, 0xa7, 0xa6, 0x9d, 0xb7, 0xd0, 0x3b, 0xfa, 0x51,
	0x10, 0x89, 0xe5, 0xf9, 0x79, 0x41, 0xfe, 0x8d, 0xde, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x60, 0x62, 0xc8, 0x9b, 0x04, 0x00, 0x00,
}
