apiVersion: v2
name: scorpicode
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: nginx
    version: 5.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
  - name: mongodb
    version: 7.8.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mongodb.enabled
