# dev values

common:
  enabled: false

frontend:
  enabled: false

hats:
  enabled: false

website:
  enabled: false

roxie:
  enabled: false

debugger:
  enabled: false
  
ingress:
  enabled: false

nginx:
  enabled: false

mongodb:
  enabled: true
  mongodbUsername: hats
  mongodbPassword: hats
  mongodbDatabase: hats
  service:
    type: LoadBalancer

rabbitmq-ha:
  enabled: true
  managementUsername: rabbit
  managementPassword: rabbit
  rabbitmqUsername: rabbit
  rabbitmqPassword: rabbit
  replicaCount: 1
  service:
    type: LoadBalancer
  prometheus:
    operator:
      enabled: false

redis:
  enabled: false
