{{- if .Values.roxie.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.roxie.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Values.roxie.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Values.roxie.name }}  
    spec:
      containers:
      - name: {{ .Values.roxie.name }}
        image: {{ .Values.common.repository }}{{ .Values.roxie.name }}:{{ .Values.roxie.tag }}
        imagePullPolicy: {{ .Values.common.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.roxie.limitsMemory | quote }}
            cpu: {{ .Values.roxie.limitsCpu | quote }}
        ports:
        - containerPort: {{ .Values.roxie.port }}
          name: http
        env:
{{- with .Values.website }}
{{ include "service.shared" . | indent 8 }}
{{- end }} 
{{ include "common.shared" . | indent 8 }}
        - name: WEBSITE_PREFIX
          value: {{ .Values.roxie.websitePrefix | quote }}
        - name: FRONTEND_PREFIX
          value: {{ .Values.roxie.frontendPrefix | quote }}
        - name: HATS_PREFIX
          value: {{ .Values.roxie.hatsPrefix | quote }}
        - name: ENABLE_CORS
          value: {{ .Values.roxie.enableCors | quote }}
        - name: LOGIN_SUCCESS_TARGET
          value: {{ .Values.website.loginSuccessTarget | quote }}
        - name: AUTH0_CLIENT_ID
          value: {{ .Values.website.auth0ClientId | quote }}
        - name: AUTH0_CLIENT_SECRET
          value: {{ .Values.website.auth0ClientSecret | quote }}
        - name: AUTH0_REDIRECT_URI
          value: {{ .Values.website.auth0RedirectUri | quote }}
{{- end }}
