{{- if .Values.soxie.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.soxie.name }}
spec:
  type: {{ .Values.soxie.serviceType }}
  ports:
    - name: http
      port: {{ .Values.soxie.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Values.soxie.name }}
{{- end }}
