{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Values.roxie.name }}
            servicePort: {{ .Values.roxie.port }}
        - path: /sc/
          backend:
            serviceName: {{ .Values.roxie.name }}
            servicePort: {{ .Values.roxie.port }}
  {{- end }}
