name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Dependencies
      working-directory: ./backend
      run: |
        go get -u golang.org/x/lint/golint
        go get -v -t -d ./...

    - name: Vet
      working-directory: ./backend
      run: |
        go vet ./...
        golint -set_exit_status ./...

    - name: Unit Test
      working-directory: ./backend
      run: go test ./... -short -v

    - name: Write Checksum Tags
      working-directory: .
      run: |
        ./devops/scripts/write-tags.sh
        cat ./devops/helmchart/tags.yaml

    - name: Docker Build
      working-directory: .
      run: |
        ./devops/scripts/docker-build.sh
  