name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GKE_CLUSTER: test
  GKE_ZONE: us-west1-a
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GCR_HOSTNAME: ${{ secrets.GCR_HOSTNAME }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.2
      id: go

    - name: Get Dependencies
      working-directory: ./backend
      run: |
        go get -u golang.org/x/lint/golint
        go get -v -t -d ./...

    - name: Vet
      working-directory: ./backend
      run: |
        go vet ./...
        golint -set_exit_status ./...

    - name: Unit Test
      working-directory: ./backend
      run: go test ./... -short -v

    - name: Write Checksum Tags
      working-directory: .
      run: |
        ./devops/scripts/write-tags.sh
        cat ./devops/helmchart/tags.yaml

    - name: Docker Build
      working-directory: .
      run: |
        docker images
        GO111MODULE=on go get github.com/mikefarah/yq/v3
        bash ./devops/scripts/docker-build.sh
        docker images
  
    - name: Minikube
      working-directory: .
      run: |
        sudo apt-get update 
        wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        minikube version
        minikube start --driver=docker
        minikube status
  
    - name: Install Helm
      working-directory: .
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

    # TODO: sops is not setup... using dev.yaml for integration tests
    - name: Helm Upgrade Dev
      working-directory: .
      run: |
        ./devops/scripts/helm-upgrade.sh dev
        sleep 10
        kubectl get po -n dev
        kubectl wait --for=condition=ready pod -l release=scorpicode --timeout=180s -n dev
        kubectl get po -n dev

    - name: Integration Tests
      working-directory: .
      run: |
        ./devops/scripts/integration-tests.sh dev
        helm delete scorpicode -n dev         

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # TODO: branch name is not an env var??? https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
    - name: Docker Push
      working-directory: .
      run: |
        bash ./devops/scripts/docker-push.sh master

    # gcloud default login
    - run: gcloud auth application-default login

    - uses: rmb938/sops-decrypt-action@master
      with:
        secrets-directory: secrets

    - name: Helm Upgrade Master
      working-directory: .
      run: |
        ./devops/scripts/helm-upgrade.sh master
        sleep 10
        kubectl get po -n master
        kubectl wait --for=condition=ready pod -l release=scorpicode --timeout=180s -n master
        kubectl get po -n master
  
    - name: Zip Helmchart
      working-directory: .
      run: tar cvzf helmchart-${{ github.run_number }}-${{ github.sha }}.tar.gz ./devops/helmchart/

    - name: Upload Helmchart Artifact
      uses: actions/upload-artifact@v1
      with:
        name: helmchart-${{ github.run_number }}-${{ github.sha }}.tar.gz
        path: helmchart-${{ github.run_number }}-${{ github.sha }}.tar.gz
